Release [v1.0.0]
babbel/terraform-aws-ecs-fargate-scheduled-task pull request #1
Opened 2019-11-11 17:36 UTC by rickybasse

## Release [v1.0.0]

This PR contains: 

* Terraform code for creating a Scheduled Fargate Task in AWS ECS
* Terraform code with a complete usage example 
* Github Actions workflow with linting and validation
* Documentation

2019-11-11 22:39 UTC, Dimwest requested changes
Almost nothing to say, just minor comments about a typo and newlines

2019-11-11 22:39 UTC, Dimwest commented on CODE_OF_CONDACT.md
> +# Contributor Covenant Code of Conduct
typo in the filename

2019-11-11 22:39 UTC, Dimwest commented on examples/complete/task/task-definition.json
> +]
newline

2019-11-11 22:39 UTC, Dimwest commented on version
> +1.0.0
newline

2019-11-18 13:04 UTC, unsign3d commented
I put as reviewers the OSS CoP as a FYI

2019-11-18 13:05 UTC, unsign3d commented
but from the OSS point of view, it seems ok

2019-11-18 13:05 UTC, unsign3d approved these changes

2019-11-18 14:31 UTC, dzeno approved these changes

2019-11-20 09:14 UTC, merged